[package]
name = "RazerSynapse2"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.2"
rdev = "0.5.3"
slint = "1.7.1"

[build-dependencies]
slint-build = "1.7.1"